CoffeeShopSystem/CoffeeShop.Web/Controllers/TableController.cs
using CoffeeShop.Model.ModelEntity;
using CoffeeShop.Service;
using System.Linq;
using System.Web.Mvc;

namespace CoffeeShop.Web.Controllers
{
    /// <summary>
    /// Manage table
    /// </summary>
    public class TableController : Controller
    {
        // GET: Table
        ITableService tableService;
        IGroupTableService groupTableService;
        /// <summary>
        /// Khởi tạo
        /// </summary>
        /// <param name="tableService"></param>
        /// <param name="groupTableService"></param>
        public TableController(ITableService tableService, IGroupTableService groupTableService)
        {
            //Create 2 service
            this.tableService = tableService;
            this.groupTableService = groupTableService;
        }

        /// <summary>
        /// View index
        /// </summary>
        /// <returns>List<Table>, List<ViewBag.GroupTable></returns>
        public ActionResult Search()
        {
            //Gọi service GetByShop
            ViewBag.GroupTable = this.groupTableService.GetByShop(1);
            return View(this.tableService.GetByShop(1)); //Trả về danh sách table của shop
        }

        /// <summary>
        /// Cập nhật table
        /// </summary>
        /// <param name="table">Table</param>
        /// <returns>Json</returns>
        [HttpPost]
        public ActionResult Edit(Table table)
        {
            //Gọi service Update
            tableService.Update(table);
            //Save dữ liệu
            tableService.Save();
            return Json("", JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Thêm table
        /// </summary>
        /// <param name="table">Table</param>
        /// <returns>Json(ID, Name, GroupTableName, GroupTableID, OrderCount, Des)</returns>
        [HttpPost]
        public ActionResult Add(Table table)
        {
            //Gọi service Add
            tableService.Add(table);
            //Save
            tableService.Save();
            //Gọi service GetByID của grouptable lấy thông tin của group
            var resultGroupTable = groupTableService.GetSingleById(table.GroupTableID);
            var data = new
            {
                ID = table.ID,
                Name = table.Name,
                GroupTableName = resultGroupTable.Name,
                GroupTableID = resultGroupTable.ID,
                OrderCount = 0, Des = table.Description
            };
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Xóa table
        /// </summary>
        /// <param name="ID">int</param>
        /// <returns>Json<true, false></returns>
        [HttpPost]
        public ActionResult Delete(int ID)
        {
            //Gọi service Delele
            return Json(tableService.Delete(ID), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Search theo tình trạng của option
        /// </summary>
        /// <param name="option">bool</param>
        /// <returns>Json(List<data>, bool>)</returns>
        [HttpPost]
        public ActionResult SearchCondition(bool delete)
        {
            //Gọi service SearchCondition
            //gán kết quả trả về
            var resultToReturn = new
            {
                data = tableService.SearchCondition(delete),
                delete = delete
            };
            return Json(resultToReturn, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Phục hồi tình trạng xóa của Table
        /// </summary>
        /// <param name="ID">int</param>
        /// <returns>Json<true, false></returns>
        [HttpPost]
        public ActionResult Recover(int ID)
        {
            //Gọi service Recover
            return Json(tableService.Recover(ID), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Search nâng cao
        /// </summary>
        /// <param name="name">string</param>
        /// <param name="groupTableID">int</param>
        /// <param name="delete">bool</param>
        /// <returns>Json(List<data>, bool)</returns>
        [HttpPost]
        public ActionResult SearchAdvanced(string name, int groupTableID, bool delete)
        {
            var resultToReturn = new
            {
                data = tableService.SearchAdvanced(name, groupTableID, delete),
                delete = delete
            };
            //Gọi service SearchAdvanced
            return Json(resultToReturn, JsonRequestBehavior.AllowGet);
        }
    }
}

CoffeeShopSystem/CoffeeShop.Web/Views/Table/Search.cshtml
@model IEnumerable<CoffeeShop.Model.ModelEntity.Table>

@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section css {
    <link href="~/Asserts/DataTables-1.10.15/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/Asserts/DuyVM2.css" rel="stylesheet" />
}
<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>DANH SÁCH BÀN</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li style="float:right">
                    <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>

        <div class="x_content" style="display: block;">
            <div class="row">
                <div class="col-sm-8">
                    <form>
                        @*<label class="radio-inline">
                                <input type="radio" name="option" value="all" checked="checked">Hiển thị tất cả
                            </label>*@
                        <label class="radio-inline">
                            <input type="radio" name="option" checked="checked" value="false">Đang quản lý
                        </label>
                        <label class="radio-inline">
                            <input type="radio" id="check" name="option" value="true">Đã xóa
                        </label>
                    </form>
                </div>

            </div>
            <div class="panel panel-default panel-table" style="margin-top: 20px">
                <div class="addbtn">
                    <a href="javascript:;" id="AddButton" title="Thêm mới" class="btn btn-success"><i class="glyphicon glyphicon-plus"></i></a>
                </div>
                <div class="lengthpage">
                    <div class="float-left">
                        <select class="form-control text-center" id="lengthpage">
                            <option value="0" disabled>Hiển thị</option>
                            <option value="5">5</option>
                            <option selected value="10">10</option>
                            <option value="20">50</option>
                            <option value="-1">Tất cả</option>
                        </select>
                    </div>
                </div>
                <a style="float: right; margin-top: 5px" data-click="0" href="javascript:;" id="AddvancedButton" title="Chuyển tùy chọn tìm kiếm" class="btn btn-danger"><i class="fa fa-cogs"></i></a>
                <div class="searchbox">

                    <div id="basesearch" class="searchbox-hiden">
                        <div class="form-groups">
                            <div class="col-sm-12">
                                <input type="text" id="search" title="Tên bàn, nhóm bàn, số lượng, mô tả ..." class="form-control" placeholder="Từ khóa">
                            </div>
                        </div>
                    </div>
                    <div id="advancedsearch" class="hidden searchbox-hiden">
                        <form id="SearchAdvancedForm" action="@Url.Action("SearchAdvanced", "Table")" method="post">
                            <div class="form-groups">
                                <div class="col-sm-6">
                                    <input type="hidden" name="delete" />
                                    <input type="text" id="NameSearch" name="name" class="form-control" title="Tên bàn" placeholder="Từ khóa">
                                </div>
                                <div class="col-sm-6">
                                    <select class="form-control" title="Nhóm bàn" id="GroupTableIDSearch" name="groupTableID">
                                        <option value="0">---Tất cả---</option>
                                        @foreach (var item in ViewBag.GroupTable)
                                        {
                                            <option value="@item.ID">@item.Name</option>
                                        }
                                    </select>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="panel-body clearfix">
                    <table id="Table" class="table table-striped table-responsive jambo_table bulk_action">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Tên</th>
                                <th>Nhóm</th>
                                <th>Đặt bàn</th>
                                <th>Mô tả</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody id="BodyTable">
                            @foreach (var item in Model)
                            {
                                <tr id="item-@item.ID">
                                    <td>@item.ID</td>
                                    <td>@item.Name</td>
                                    <td>@item.GroupTable.Name</td>
                                    <td>@item.Orders.Count(o => o.Status != true)</td>
                                    <td>@item.Description</td>
                                    <td>
                                        <a href="javascript:;" class="_edit btn btn-info btn-xs" data-id="@item.ID" data-name="@item.Name" data-grouptableid="@item.GroupTableID" data-description="@item.Description" title="Sửa"><i class="fa fa-pencil"></i></a>
                                        <a href="javascript:;" class="_delete btn btn-danger btn-xs" data-id="@item.ID" data-toggle="modal" data-target="#DeleteModal" title="Xóa"><i class="fa fa-trash-o"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Modal Add-->
<div class="modal fade" id="AddModal" role="dialog">
    <div class="modal-dialog" style="width:700px">
        <div class="modal-content">
            <form id="AddForm" method="post" action="@Url.Action("Add", "Table")" class="form-horizontal">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Thêm Bàn Mới</h4>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="ID" />
                    <div class="form-group">
                        <label class="control-label col-sm-2">Tên:</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="Name" placeholder="Tên">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2">Nhóm bàn:</label>
                        <div class="col-sm-10">
                            <select class="form-control" name="GroupTableID">
                                <option value="0">---Chọn nhóm bàn---</option>
                                @foreach (var item in ViewBag.GroupTable)
                                {
                                    <option value="@item.ID">@item.Name</option>
                                }
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2">Mô tả:</label>
                        <div class="col-sm-10">
                            <textarea class="form-control" rows="3" name="Description" placeholder="Mô tả"></textarea>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary savebutton">Lưu</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Hủy</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal Edit-->
<div class="modal fade" id="EditModal" role="dialog">
    <div class="modal-dialog" style="width:700px">
        <div class="modal-content">
            <form id="EditForm" method="post" action="@Url.Action("Edit", "Table")" class="form-horizontal">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="text-center">Chỉnh Sửa Bàn</h4>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="ID">
                    <div class="form-group">
                        <label class="control-label col-sm-2">Tên:</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name="Name" placeholder="tên">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2">Nhóm bàn:</label>
                        <div class="col-sm-10">
                            <select class="form-control" name="GroupTableID">
                                @foreach (var item in ViewBag.GroupTable)
                                {
                                    <option value="@item.ID">@item.Name</option>
                                }
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2">Mô tả:</label>
                        <div class="col-sm-10">
                            <textarea class="form-control" rows="3" name="Description" placeholder="Mô tả"></textarea>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary savebutton">Lưu</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Hủy</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!--Delete Modal-->
<div class="modal fade" id="DeleteModal" role="dialog">
    <div class="modal-dialog" style="width:700px">
        <div class="modal-content">
            <form id="DeleteForm" method="post" action="@Url.Action("Delete", "Table")">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 style="text-align: center">Xác Nhận</h4>
                </div>
                <div class="modal-body">
                    <h5 class="text-center">Bạn chắc chắn xóa?</h5>
                    <input type="hidden" name="ID" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary savebutton" data-dismiss="modal">Đồng ý</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Hủy</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!--Recover Modal-->
<div class="modal fade" id="RecoverModal" role="dialog">
    <div class="modal-dialog" style="width:700px">
        <div class="modal-content">
            <form id="RecoverForm" method="post" action="@Url.Action("Recover", "Table")">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 style="text-align: center">Xác Nhận</h4>
                </div>
                <div class="modal-body">
                    <h5 class="text-center">Bạn chắc chắn phục hồi?</h5>
                    <input type="hidden" name="ID" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary savebutton" data-dismiss="modal">Đồng ý</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Hủy</button>
                </div>
            </form>
        </div>
    </div>
</div>
@section js {
    <!--js-->
    <script src="~/Asserts/DataTables-1.10.15/js/jquery.dataTables.min.js"></script>
<script src="~/Asserts/DataTables-1.10.15/js/dataTables.bootstrap.min.js"></script>
    <script src="~/Asserts/jquery-validation-1.17.0/jquery.validate.min.js"></script>
    <script src="~/Scripts/Table.js"></script>
}